# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_assets.calc.calc_pb2 as calc__pb2


class CalcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/Calc/add',
                request_serializer=calc__pb2.Inp.SerializeToString,
                response_deserializer=calc__pb2.Result.FromString,
                )
        self.subtract = channel.unary_unary(
                '/Calc/subtract',
                request_serializer=calc__pb2.Inp.SerializeToString,
                response_deserializer=calc__pb2.Result.FromString,
                )
        self.multiply = channel.unary_unary(
                '/Calc/multiply',
                request_serializer=calc__pb2.Inp.SerializeToString,
                response_deserializer=calc__pb2.Result.FromString,
                )
        self.divide = channel.unary_unary(
                '/Calc/divide',
                request_serializer=calc__pb2.Inp.SerializeToString,
                response_deserializer=calc__pb2.Result.FromString,
                )


class CalcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calc__pb2.Inp.FromString,
                    response_serializer=calc__pb2.Result.SerializeToString,
            ),
            'subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.subtract,
                    request_deserializer=calc__pb2.Inp.FromString,
                    response_serializer=calc__pb2.Result.SerializeToString,
            ),
            'multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.multiply,
                    request_deserializer=calc__pb2.Inp.FromString,
                    response_serializer=calc__pb2.Result.SerializeToString,
            ),
            'divide': grpc.unary_unary_rpc_method_handler(
                    servicer.divide,
                    request_deserializer=calc__pb2.Inp.FromString,
                    response_serializer=calc__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calc/add',
            calc__pb2.Inp.SerializeToString,
            calc__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calc/subtract',
            calc__pb2.Inp.SerializeToString,
            calc__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calc/multiply',
            calc__pb2.Inp.SerializeToString,
            calc__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calc/divide',
            calc__pb2.Inp.SerializeToString,
            calc__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
